name: WinISO

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  winiso:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: unzip *.zip

      - run: ls

      - run: (Get-Content uup_download_windows.cmd -Encoding UTF8) | foreach { $_ -replace "powershell","pwsh" } | Set-Content uup_download_windows.cmd -Encoding UTF8

      - run: cat uup_download_windows.cmd
    
